import { ColumnHeaderData, FilterType } from 'libs/tds-component-library/src';

export const exampleColumnModel: ColumnHeaderData[] = [
	{
		label: 'Task Number',
		property: 'taskNumber',
		filterType: FilterType.text,
		width: 150,
	},
	{
		label: 'Boolean Example',
		property: 'someBooleanValue',
		filterType: FilterType.boolean,
		filterInputData: {
			data: [
				{
					text: 'Yes',
					value: true,
				},
				{
					text: 'No',
					value: false,
				},
			],
			defaultItem: { text: 'Please Select', value: null },
		},
		width: 150,
	},
	{
		label: 'Description',
		property: 'comment',
		filterType: FilterType.text,
		width: 150,
	},
	{
		label: 'Asset Type',
		property: 'assetEntityAssetType',
		filterType: FilterType.text,
		width: 150,
	},
	{
		label: 'Asset Class',
		property: 'assetEntityAssetClass',
		filterType: FilterType.dropdown,
		filterInputData: {
			data: [
				{
					text: 'application',
					value: 'APPLICATION',
				},
				{
					text: 'device',
					value: 'DEVICE',
				},
				{
					text: 'storage',
					value: 'STORAGE',
				},
			],
			defaultItem: { text: 'Please Select', value: null },
		},
		width: 150,
	},
	{
		label: 'Date',
		property: 'userSelectedCol2',
		filterType: FilterType.date,
		width: 150,
		format: 'dd-MMM-yyyy',
	},
];

export const exampleGridData = [
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: true,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: 'APPLICATION',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: true,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Hold',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: 'APPLICATION',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: true,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Pending',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: true,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Completed',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: true,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: 'APPLICATION',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: true,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: false,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: 'STORAGE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: 'STORAGE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: false,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: false,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: false,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: false,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236955,
		taskNumber: 18266,
		comment: 'Task - by CN',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:31 PM',
		updatedTime: '19h 29m',
		dueDate: '',
		status: 'Ready',
		userSelectedCol2: '12/09/2028 09:00 PM',
		userSelectedCol3: 'SYS_ADMIN',
		userSelectedCol4: '24/09/2019 03:57 PM',
		score: 614,
		taskStatus: 'task_ready',
		dueClass: '',
		assetEntityId: 147814,
		assetEntityAssetType: 'Appliance',
		assetEntityAssetClass: 'DEVICE',
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: '',
		someBooleanValue: false,
	},
	{
		id: 236975,
		taskNumber: 18286,
		comment: '4 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '30/09/2019 04:29 PM',
		updatedTime: '19h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: false,
	},
	{
		id: 236979,
		taskNumber: 18289,
		comment: '5 am',
		userSelectedCol0: 'general',
		userSelectedCol1: '29/09/2019 04:29 PM',
		updatedTime: '18h 31m',
		dueDate: '',
		status: 'Started',
		userSelectedCol2: '13/09/2028 09:45 PM',
		userSelectedCol3: '',
		userSelectedCol4: '30/09/2019 04:07 PM',
		nGraphUrl: 0,
		score: 714,
		taskStatus: 'task_started',
		dueClass: '',
		assetEntityId: null,
		assetEntityAssetType: null,
		assetEntityAssetClass: null,
		instructionsLinkURL: null,
		estStartClass: null,
		estFinishClass: null,
		isPublished: true,
		updatedClass: 'task_late',
		someBooleanValue: true,
	},
];
