
export const FA_ICONS = {
	faList: ['fas', 'list'],
	faLayerGroup: ['fas', 'layer-group'],
	faBars: ['fas', 'bars'],
	faServer: ['fas', 'server'],
	faDatabase: ['fas', 'database'],
	faBoxOpen: ['fas', 'box-open'],
	faCircle: ['fas', 'circle'],
	faCog: ['fas', 'cog'],
	faCogs: ['fas', 'cogs'],
	faSyncAlt: ['fas', 'sync-alt'],
	faSortAmountDown: ['fas', 'sort-amount-down'],
	faAdjust: ['fas', 'adjust'],
	faSearchPlus: ['fas', 'search-plus'],
	faSearchMinus: ['fas', 'search-minus'],
	faTruck: ['fas', 'cubes'],
	faSitemap: ['fas', 'sitemap'],
	faListUl: ['fas', 'list-ul'],
	faMinus: ['fas', 'minus'],
	faCheck: ['fas', 'check'],
	faForward: ['fas', 'forward'],
	faSignal: ['fas', 'signal'],
	faStream: ['fas', 'stream'],
	faUsers: ['fas', 'users'],
	faWindowClose: ['fas', 'window-close'],
	faEdit: ['fas', 'edit'],
	faEye: ['fas', 'eye'],
	faUser: ['fas', 'user'],
	faUndo: ['fas', 'undo'],
	faHome: ['fas', 'home'],
	faBuilding: ['fas', 'building']
};
