import {Component} from '@angular/core';

@Component({
	selector:  'app-grid-task-manager',
	templateUrl:  './grid-task-manager.component.html',
	styleUrls:  ['./grid-task-manager.component.scss']
})
export class GridTaskManagerComponent {
	public tasks = {
		rows: [
			{
				id:  229997,
				taskNumber: 11406,
				comment: 'TestAPI2 v',
				userSelectedCol0: '03/05/2018 03: 44 PM',
				userSelectedCol1: '09/27/2019 07: 51 PM',
				updatedTime: '23d 1h',
				dueDate: '',
				status: 'Completed',
				userSelectedCol2: 'TDS Admin',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'moveday',
				score: 211,
				taskStatus: 'task_completed',
				dueClass: '',
				assetEntityid:  null,
				assetEntityAssetType: null,
				assetEntityAssetClass: null,
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: '',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  230001,
				taskNumber: 11410,
				comment: '9380 Task 1',
				userSelectedCol0: '03/07/2018 09: 04 AM',
				userSelectedCol1: '03/07/2018 09: 08 AM',
				updatedTime: '1y 204d 11h',
				dueDate: '08/03/2018',
				status: 'Completed',
				userSelectedCol2: '',
				userSelectedCol3: '',
				userSelectedCol4: 'general',
				score: 215,
				taskStatus: 'task_completed',
				dueClass: 'task_overdue',
				assetEntityid:  113902,
				assetEntityAssetType: 'Network',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: '',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  230002,
				taskNumber: 11411,
				comment: '9380 Task 2',
				userSelectedCol0: '03/07/2018 09: 07 AM',
				userSelectedCol1: '03/14/2018 10: 26 AM',
				updatedTime: '1y 197d 10h',
				dueDate: '',
				status: 'Completed',
				userSelectedCol2: 'Automated Task',
				userSelectedCol3: 'AUTO',
				userSelectedCol4: 'general',
				score: 115,
				taskStatus: 'task_completed',
				dueClass: '',
				assetEntityid:  144596,
				assetEntityAssetType: 'VM',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: '',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  230004,
				taskNumber: 11413,
				comment: 'Test TM-9380 succ',
				userSelectedCol0: '03/14/2018 10: 27 AM',
				userSelectedCol1: '03/14/2018 05: 31 PM',
				updatedTime: '1y 197d 3h',
				dueDate: '',
				status: 'Completed',
				userSelectedCol2: 'TDS Admin',
				userSelectedCol3: 'AUTO',
				userSelectedCol4: 'general',
				score: 115,
				taskStatus: 'task_completed',
				dueClass: '',
				assetEntityid:  null,
				assetEntityAssetType: null,
				assetEntityAssetClass: null,
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: '',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234198,
				taskNumber: 15580,
				comment: 'tm.12353 test task02',
				userSelectedCol0: '10/24/2018 04: 42 PM',
				userSelectedCol1: '10/24/2018 04: 59 PM',
				updatedTime: '338d 3h',
				dueDate: '10/24/2018',
				status: 'Completed',
				userSelectedCol2: '',
				userSelectedCol3: 'TECH',
				userSelectedCol4: 'general',
				score: 215,
				taskStatus: 'task_completed',
				dueClass: 'task_overdue',
				assetEntityid:  null,
				assetEntityAssetType: null,
				assetEntityAssetClass: null,
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: '',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234199,
				taskNumber: 15581,
				comment: 'tm-12353 second copleted task',
				userSelectedCol0: '10/24/2018 04: 57 PM',
				userSelectedCol1: '09/25/2019 08: 24 PM',
				updatedTime: '2d',
				dueDate: '10/26/2018',
				status: 'Hold',
				userSelectedCol2: '',
				userSelectedCol3: 'VM_ADMIN',
				userSelectedCol4: 'general',
				score: 915,
				taskStatus: 'task_hold',
				dueClass: 'task_late',
				assetEntityid:  null,
				assetEntityAssetType: null,
				assetEntityAssetClass: null,
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234255,
				taskNumber: 15617,
				comment: 'Startup app QAE2E VVC4s App For E2E Edited',
				userSelectedCol0: '12/11/2018 04: 13 PM',
				userSelectedCol1: '08/14/2019 02: 19 PM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'APP_COORD',
				userSelectedCol4: 'startup',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  144984,
				assetEntityAssetType: 'Application',
				assetEntityAssetClass: 'APPLICATION',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: false,
				updatedClass: ''
			},
			{
				id:  234256,
				taskNumber: 15618,
				comment: 'Startup app QAE2E J7RCf App For E2E Edited',
				userSelectedCol0: '12/11/2018 04: 13 PM',
				userSelectedCol1: '12/11/2018 04: 13 PM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'APP_COORD',
				userSelectedCol4: 'startup',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  144992,
				assetEntityAssetType: 'Application',
				assetEntityAssetClass: 'APPLICATION',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: false,
				updatedClass: ''
			},
			{
				id:  234257,
				taskNumber: 15619,
				comment: 'Startup app QAE2E VVC4s App For E2E Edited',
				userSelectedCol0: '12/11/2018 04: 14 PM',
				userSelectedCol1: '12/11/2018 04: 14 PM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'APP_COORD',
				userSelectedCol4: 'startup',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  144984,
				assetEntityAssetType: 'Application',
				assetEntityAssetClass: 'APPLICATION',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: false,
				updatedClass: ''
			},
			{
				id:  234258,
				taskNumber: 15620,
				comment: 'Startup app QAE2E J7RCf App For E2E Edited',
				userSelectedCol0: '12/11/2018 04: 14 PM',
				userSelectedCol1: '12/11/2018 04: 14 PM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'APP_COORD',
				userSelectedCol4: 'startup',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  144992,
				assetEntityAssetType: 'Application',
				assetEntityAssetClass: 'APPLICATION',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: false,
				updatedClass: ''
			},
			{
				id:  234274,
				taskNumber: 15635,
				comment: 'Regression Task - by CN',
				userSelectedCol0: '12/20/2018 05: 29 PM',
				userSelectedCol1: '12/20/2018 05: 31 PM',
				updatedTime: '281d 3h',
				dueDate: '',
				status: 'Completed',
				userSelectedCol2: 'Timo Boll',
				userSelectedCol3: '',
				userSelectedCol4: 'general',
				score: 215,
				taskStatus: 'task_completed',
				dueClass: '',
				assetEntityid:  null,
				assetEntityAssetType: null,
				assetEntityAssetClass: null,
				instructionsLinkURL: null,
				estStartClass: '',
				estFinishClass: '',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234806,
				taskNumber: 16164,
				comment: 'Re-IP and Powerdown PE-R610-17',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113785,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234807,
				taskNumber: 16165,
				comment: 'Re-IP and Powerdown A1 PDU1 A_ API TESTS',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113848,
				assetEntityAssetType: 'PDU',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234808,
				taskNumber: 16166,
				comment: 'Re-IP and Powerdown PE-R610-03',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '08/21/2019 08: 05 PM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113866,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234809,
				taskNumber: 16167,
				comment: 'Re-IP and Powerdown PE-R610-04',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113867,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234810,
				taskNumber: 16168,
				comment: 'Re-IP and Powerdown PE-R610-06',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113869,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234811,
				taskNumber: 16169,
				comment: 'Re-IP and Powerdown PE-R610-07',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113870,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234812,
				taskNumber: 16170,
				comment: 'Re-IP and Powerdown PE-R610-09',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113872,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234813,
				taskNumber: 16171,
				comment: 'Re-IP and Powerdown PE-R610-15',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113911,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234814,
				taskNumber: 16172,
				comment: 'Re-IP and Powerdown PL-DL380-01',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113948,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234815,
				taskNumber: 16173,
				comment: 'Re-IP and Powerdown Mailserver01',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113952,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234816,
				taskNumber: 16174,
				comment: 'Re-IP and Powerdown Mailserver02',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113953,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234817,
				taskNumber: 16175,
				comment: 'Re-IP and Powerdown PL-DL580-01',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113954,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234818,
				taskNumber: 16176,
				comment: 'Re-IP and Powerdown Mailserver03',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113955,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			},
			{
				id:  234819,
				taskNumber: 16177,
				comment: 'Re-IP and Powerdown Mailserver04',
				userSelectedCol0: '01/04/2019 10: 17 AM',
				userSelectedCol1: '01/04/2019 10: 17 AM',
				updatedTime: '',
				dueDate: '',
				status: 'Ready',
				userSelectedCol2: '',
				userSelectedCol3: 'SYS_ADMIN',
				userSelectedCol4: 'shutdown',
				score: 615,
				taskStatus: 'task_ready',
				dueClass: '',
				assetEntityid:  113956,
				assetEntityAssetType: 'Server',
				assetEntityAssetClass: 'DEVICE',
				instructionsLinkURL: null,
				estStartClass: 'task_late',
				estFinishClass: 'task_late',
				isPublished: true,
				updatedClass: ''
			}
		],
		totalCount: 50
	};
	public data:  any = [
		{
			name:  'Task 1',
			role:  'FE Team'
		},
		{
			name:  'Task 2',
			role:  'FE Team'
		}
	];

	constructor() {
		//
	}
}
