export const dataTaskGrid = {
	rows: [
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Hold',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Pending',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Completed',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236955,
			taskNumber: 18266,
			comment: 'Task - by CN',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			updatedTime: '19h 29m',
			dueDate: '',
			status: 'Ready',
			userSelectedCol2: '12/09/2028 09:00 PM',
			userSelectedCol3: 'SYS_ADMIN',
			userSelectedCol4: '24/09/2019 03:57 PM',
			score: 614,
			taskStatus: 'task_ready',
			dueClass: '',
			assetEntityId: 147814,
			assetEntityAssetType: 'Appliance',
			assetEntityAssetClass: 'DEVICE',
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: '',
		},
		{
			id: 236975,
			taskNumber: 18286,
			comment: '4 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			updatedTime: '19h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
		{
			id: 236979,
			taskNumber: 18289,
			comment: '5 am',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			updatedTime: '18h 31m',
			dueDate: '',
			status: 'Started',
			userSelectedCol2: '13/09/2028 09:45 PM',
			userSelectedCol3: '',
			userSelectedCol4: '30/09/2019 04:07 PM',
			nGraphUrl: 0,
			score: 714,
			taskStatus: 'task_started',
			dueClass: '',
			assetEntityId: null,
			assetEntityAssetType: null,
			assetEntityAssetClass: null,
			instructionsLinkURL: null,
			estStartClass: null,
			estFinishClass: null,
			isPublished: true,
			updatedClass: 'task_late',
		},
	],
	totalCount: 24,
};
export const columnModelTaskGrid = [
	{
		columnMenu: false,
		field: 'taskNumber',
		filterable: true,
		title: 'Task',
		locked: false,
		width: 90,
		filter: null,
		isActionable: true,
		type: 'text'
	},
	{
		columnMenu: true,
		field: 'comment',
		filterable: true,
		title: 'Description',
		locked: false,
		width: 160,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: true,
		field: 'userSelectedCol0',
		filterable: true,
		title: 'Category',
		locked: false,
		width: 160,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'userSelectedCol1',
		filterable: true,
		title: 'Last Updated',
		locked: false,
		width: 170,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'updatedtime',
		filterable: true,
		title: 'Updated',
		locked: false,
		width: 170,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'dueDate',
		filterable: true,
		title: 'Due Date',
		locked: false,
		width: 130,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'status',
		filterable: true,
		title: 'Status',
		locked: false,
		width: 130,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'userSelectedCol2',
		filterable: true,
		title: 'Estimated Start',
		locked: false,
		width: 170,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'updatedtime',
		filterable: true,
		title: 'Updated',
		locked: false,
		width: 180,
		filter: null,
		type: 'text'
	},
];
export const columnMenu = [
	'Label 1',
	'Label 2',
	'Label 3',
	'Label 4',
	'Label 5',
	'Label 6',
	'Label 7',
	'Label 8',
	'Label 9',
	'Label 10',
];

export const dataAssetsGrid = {
	rows: [
		{
			id: 236955,
			assetName: 'A1 PDU A',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			checked: false,
		},
		{
			id: 236975,
			assetName: 'A1 PDU B',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236979,
			assetName: 'A1 PDU C',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236955,
			assetName: 'A1 PDU D',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			checked: false,
		},
		{
			id: 236975,
			assetName: 'A1 PDU E',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236979,
			assetName: 'A1 PDU F',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236955,
			assetName: 'A1 PDU F',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			checked: false,
		},
		{
			id: 236975,
			assetName: 'A1 PDU G',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236955,
			assetName: 'A1 PDU A',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			checked: false,
		},
		{
			id: 236975,
			assetName: 'A1 PDU B',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236979,
			assetName: 'A1 PDU C',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236955,
			assetName: 'A1 PDU D',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			checked: false,
		},
		{
			id: 236975,
			assetName: 'A1 PDU E',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236979,
			assetName: 'A1 PDU F',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '29/09/2019 04:29 PM',
			checked: false,
		},
		{
			id: 236955,
			assetName: 'A1 PDU F',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:31 PM',
			checked: false,
		},
		{
			id: 236975,
			assetName: 'A1 PDU G',
			comment: '',
			userSelectedCol0: 'general',
			userSelectedCol1: '30/09/2019 04:29 PM',
			checked: false,
		},
	],
	totalCount: 16,
};

export const columnModelAssetsGrid = [
	{
		columnMenu: false,
		field: 'assetName',
		filterable: true,
		title: 'Name',
		locked: false,
		width: 160,
		filter: null,
		isActionable: true,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'comment',
		filterable: true,
		title: 'Description',
		locked: false,
		width: 160,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: true,
		field: 'userSelectedCol0',
		filterable: true,
		title: 'Category',
		locked: false,
		width: 160,
		filter: null,
		type: 'text'
	},
	{
		columnMenu: false,
		field: 'userSelectedCol1',
		filterable: true,
		title: 'Last Updated',
		locked: false,
		width: 170,
		filter: null,
		type: 'text'
	},
];
